name: CI

on:
  pull_request:
    branches: [master]
  push:
    paths-ignore:
      - '**.md'
      - 'image/*'
    branches: [master, 'ci/**']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version: [30.1, snapshot]
        ignore_warnings:
          - true

    steps:
      - uses: actions/checkout@v4

      - name: Install emacs (Linux)
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Melpa style check
        uses: leotaku/elisp-check@master
        with:
          check: melpa
          file: 'md.el'
          ignore_warnings: false
          warnings_as_errors: false
